git:
  submodules: false
jobs:
  include:
    - stage: test
      name: "Debian"
      os: linux
      dist: bionic
      language: c
      install: ./.travis/install-debian.sh
      script: ./.travis/build-debian.sh
    - stage: deploy
      name: "OSX"
      os: osx
      osx_image: xcode8.3
      language: c
      install: ./.travis/install-macos.sh
      # the awk command is a workaround for https://github.com/travis-ci/travis-ci/issues/4704.
      script: ./.travis/build-macos.sh | awk '/.{0,32}/ {print $0}'
      deploy:
        provider: releases
        api_key:
          secure: dDlkIawHcODlW9B/20/cQCtzeoocvs0hKuNngRKXKqzXLWTRq33oq/B7+39tAixWbmv6exTpijiKrRNFiSCW5Z4iwHLwaRD4XJznxw63e/Hus/dxg2Tvqx7XFpkCz8mT1Z+gZQE5YxAngeZPpI/sZbZtF1UO3yH5eLeeokZ15p26ZskQUPoYuzrTgTzYL3XfpG3F+20rNBawH1ycsCTVD/08/n31d2m3CrKAsbW7er92ek6w4fzKr7NW8WeXjrPJETVpw5fQg1Od3pRGW8dPQaJcvKQEogMp8Mm0ETYd0qigg89/giBz7QwOgmAWQ4dH+DfZH4Ojl//127QztBolMvyDMQBykWrtJoGcij05sT6K2IJr2FHeUBO12MAEdjiVvhQj3DtTzjPiZAHHDBSLWxLKWWhlhHE4pq7g1MQhqXkaAHI2BLNzwLmaowbMT0bECf9yfz6xx18h6XPQFX44oOktraobVALFlyHqeKa8zdcUt22LF6uAL1m5dxL0tny3eXCIPE4UH/RZgua/cHV9G3cUvKQa/QnFSLRhvWVSbGB+7YsHouBJcsUOOW1gmd5442XuC7mpppccRldh+GSxUk6TBJRAx7TeQ0ybDUaoco9MUqp2twv3KreR2+8Q12PDaAhfQVNEGdF3wTm1sShImjCN4VN3eSLlBEbve1QRQXM=
        skip_cleanup: true
        file: build/SolveSpace.dmg
        on:
          repo: solvespace/solvespace
          tags: true
    - &deploy-snap
      stage: deploy
      name: Snap amd64
      os: linux
      arch: amd64
      dist: bionic
      addons:
        snaps:
          - name: snapcraft
            confinement: classic
      script: ./.travis/build-snap.sh
      deploy:
        - provider: script
          script: sudo ./.travis/deploy-snap.sh edge
          skip_cleanup: true
          on:
            branch: master
            tags: false
        - provider: script
          script: sudo ./.travis/deploy-snap.sh edge,beta
          skip_cleanup: true
          on:
            repo: solvespace/solvespace
            tags: true
    - <<: *deploy-snap
      name: Snap arm64
      arch: arm64
    - &linux
      stage: deploy
      os: linux
      sudo: required
      dist: bionic
      language: python
      python: "3.6"
      addons:
        apt:
          update: true
          packages:
            - patchelf
      install: &python-install
        - python3 -m pip install -r cython/requirements.txt
      script: &python-script
        - cd cython && python3 setup.py test && cd -
      before_deploy: cd cython
      deploy:
        - provider: pypi
          user: $TWINE_USERNAME
          password: $TWINE_PASSWORD
          skip_cleanup: true
          skip_existing: true
          distributions: sdist
          on:
            repo: KmolYuan/solvespace
            tags: true
    - <<: *linux
      python: "3.7"
    - <<: *linux
      python: "3.8"
    - &osx
      stage: deploy
      os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=3.6.0
      before_install:
        - brew update
        - brew upgrade pyenv || true
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv install ${PYTHON}
        - pyenv global ${PYTHON}
        - python3 -m pip install pip -U
        - python3 --version
        - python3 -m pip --version
      install: *python-install
      script: *python-script
      after_success:
        # PyPI deployment
        - if [[ "$TRAVIS_REPO_SLUG" == "KmolYuan/solvespace" && -n "$TRAVIS_TAG" ]]; then
          python3 -m pip install twine;
          cd cython;
          python3 setup.py bdist_wheel;
          python3 -m twine upload dist/*.whl --skip-existing;
          fi
    - <<: *osx
      env: PYTHON=3.7.0
    - <<: *osx
      env: PYTHON=3.8.0
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
